site_name: Tutorial DJC
site_favicon: img/icon.png
site_url: https://tutorial-hub.djc.pe/

nav:
  # - DJC: https://www.djc.pe/
  - Price: https://www.djc.pe/price/
  - Tutorial: https://tutorial-hub.djc.pe/

theme:
  name: mkdocs
  custom_dir: overrides
  locale: es
  user_color_mode_toggle: yes
  color_mode: auto

extra_css:
  - extra_css/color.css

hooks:
  - hooks/description.py

plugins:
  # - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          # default: true
          name: Espa√±ol
          build: true
